package com.trustlink.service;

import com.trustlink.exception.ApiException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.core.io.UrlResource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Map;
import java.util.UUID;

/**
 * Local-disk storage for verification documents - fine for one hackathon demo
 * instance, not for anything horizontally scaled or redeployed (see the README and
 * the app.storage.verification-upload-dir comment in application.yml).
 *
 * Security properties that matter more than the storage backend choice:
 *  - allowlist of exactly three content types, checked against the file's actual
 *    magic bytes, not just the client-declared Content-Type header (trivially spoofed)
 *  - the stored filename is always a fresh random UUID - the client's original
 *    filename is kept only as display metadata, never used to build a filesystem path
 *  - size is capped independently of the global Spring multipart limit, so this check
 *    still holds even if that config ever drifts
 */
@Service
public class FileStorageService {

    private static final Map<String, byte[]> MAGIC_BYTES = Map.of(
        "image/jpeg", new byte[]{(byte) 0xFF, (byte) 0xD8, (byte) 0xFF},
        "image/png", new byte[]{(byte) 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A},
        "application/pdf", new byte[]{0x25, 0x50, 0x44, 0x46} // "%PDF"
    );

    private static final Map<String, String> EXTENSIONS = Map.of(
        "image/jpeg", ".jpg",
        "image/png", ".png",
        "application/pdf", ".pdf"
    );

    private final Path uploadDir;
    private final long maxFileSizeBytes;

    public FileStorageService(
        @Value("${app.storage.verification-upload-dir}") String uploadDir,
        @Value("${app.storage.max-verification-file-size-bytes}") long maxFileSizeBytes
    ) {
        this.uploadDir = Path.of(uploadDir).toAbsolutePath().normalize();
        this.maxFileSizeBytes = maxFileSizeBytes;
        try {
            Files.createDirectories(this.uploadDir);
        } catch (IOException e) {
            throw new IllegalStateException("Could not create upload directory: " + this.uploadDir, e);
        }
    }

    public record StoredFile(String storedFileName, String originalFileName, String contentType, long sizeBytes) {}

    public StoredFile store(MultipartFile file) {
        if (file == null || file.isEmpty()) {
            throw ApiException.badRequest("No file was uploaded.");
        }
        if (file.getSize() > maxFileSizeBytes) {
            throw ApiException.badRequest("File exceeds the " + (maxFileSizeBytes / 1024 / 1024) + "MB limit.");
        }

        String declaredType = file.getContentType();
        String extension = EXTENSIONS.get(declaredType);
        if (extension == null) {
            throw ApiException.badRequest("Only JPEG, PNG or PDF files are accepted.");
        }
        verifyMagicBytes(file, declaredType);

        String storedFileName = UUID.randomUUID() + extension;
        Path target = uploadDir.resolve(storedFileName);

        try (InputStream in = file.getInputStream()) {
            Files.copy(in, target, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR, "Could not save the uploaded file.");
        }

        String originalName = sanitizeDisplayName(file.getOriginalFilename());
        return new StoredFile(storedFileName, originalName, declaredType, file.getSize());
    }

    public Resource load(String storedFileName) {
        // storedFileName always came from our own DB, generated by store() above - it's
        // never user input at this call site - but we still refuse to resolve anything
        // containing a path separator, as cheap defence in depth.
        if (storedFileName.contains("/") || storedFileName.contains("\\") || storedFileName.contains("..")) {
            throw ApiException.badRequest("Invalid file reference.");
        }
        try {
            Path file = uploadDir.resolve(storedFileName).normalize();
            if (!file.startsWith(uploadDir)) {
                throw ApiException.badRequest("Invalid file reference.");
            }
            Resource resource = new UrlResource(file.toUri());
            if (!resource.exists() || !resource.isReadable()) {
                throw ApiException.notFound("File not found.");
            }
            return resource;
        } catch (MalformedURLException e) {
            throw ApiException.notFound("File not found.");
        }
    }

    private void verifyMagicBytes(MultipartFile file, String declaredType) {
        byte[] expected = MAGIC_BYTES.get(declaredType);
        byte[] actual = new byte[expected.length];
        try (InputStream in = file.getInputStream()) {
            int read = in.readNBytes(actual, 0, actual.length);
            if (read < actual.length) {
                throw ApiException.badRequest("File is empty or corrupted.");
            }
        } catch (IOException e) {
            throw ApiException.badRequest("Could not read the uploaded file.");
        }
        for (int i = 0; i < expected.length; i++) {
            if (actual[i] != expected[i]) {
                throw ApiException.badRequest(
                    "The file's contents don't match its declared type (" + declaredType + ")."
                );
            }
        }
    }

    /** Strips anything that isn't safe to echo back or use in a Content-Disposition header. */
    private String sanitizeDisplayName(String originalFilename) {
        if (originalFilename == null || originalFilename.isBlank()) {
            return "document";
        }
        String nameOnly = Path.of(originalFilename).getFileName().toString();
        return nameOnly.replaceAll("[^a-zA-Z0-9 ._-]", "_");
    }
}
